version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: rea_postgres_test
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d myapp_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rea_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rea_pgadmin_test
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rea_network

volumes:
  postgres_data:

networks:
  rea_network:
    driver: bridge