# REA INVEST Prometheus Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'rea-invest-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rules configuration
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # REA INVEST Backend API
  - job_name: 'rea-invest-backend'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # REA INVEST Frontend
  - job_name: 'rea-invest-frontend'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics
    scrape_timeout: 10s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Nginx Reverse Proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Node Exporter (System metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['172.17.0.1:9323']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Custom application metrics
  - job_name: 'rea-invest-custom-metrics'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 30s
    metrics_path: /api/metrics/custom
    scrape_timeout: 10s

  # Health checks monitoring
  - job_name: 'rea-invest-health-checks'
    static_configs:
      - targets:
        - 'backend:8000'
        - 'frontend:3000'
        - 'postgres:5432'
        - 'redis:6379'
    scrape_interval: 15s
    metrics_path: /health
    scrape_timeout: 5s
    honor_labels: true

# Remote write configuration (optional, for external storage)
# remote_write:
#   - url: "https://your-remote-storage.com/api/prom/push"
#     basic_auth:
#       username: "username"
#       password: "password"

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB

# Global limits
global_config:
  scrape_timeout: 10s
  scrape_interval: 15s
  evaluation_interval: 15s